version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./app:/home/app
      - ./config/nginx:/etc/nginx/conf.d
      - django-static:/home/static
      - django-media:/home/app/media
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    volumes:
      - ./app:/home/app
      - django-static:/home/static
      - django-media:/home/app/media
    expose:
      - "8000"
    command: >
      sh -c "python manage.py collectstatic --no-input &&
             python manage.py wait_for_db &&
             python manage.py makemigrations core &&
             python manage.py migrate &&
             gunicorn app.wsgi -b 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
  db:
    image: postgres:11
    container_name: ps01
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
volumes:
  django-static:
  django-media:
  pgdata:
