# Generated by Django 2.2.2 on 2019-07-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
