# Generated by Django 2.2.4 on 2019-08-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190814_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='google_maps',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
