# Generated by Django 2.2.2 on 2019-07-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190708_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
