# Generated by Django 2.2.2 on 2019-06-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190610_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social',
            new_name='Contact',
        ),
    ]
