# Generated by Django 2.2.2 on 2019-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190708_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='slug',
            field=models.SlugField(),
        ),
    ]
