# Generated by Django 2.2.4 on 2019-09-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Secret',
        ),
    ]
