# Generated by Django 2.2.2 on 2019-06-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_promoter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
