# Generated by Django 2.2.2 on 2019-06-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190616_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artists',
        ),
    ]
