# Generated by Django 2.2.4 on 2019-09-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
