# Generated by Django 2.2.2 on 2019-07-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190708_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets_remaining',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='core.Event')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.TicketType'),
            preserve_default=False,
        ),
    ]
