# Generated by Django 2.2.2 on 2019-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190708_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
