# Generated by Django 2.2.5 on 2019-11-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ticket_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.Tally'),
        ),
    ]
