# Generated by Django 2.2.2 on 2019-06-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artists',
        ),
        migrations.AddField(
            model_name='artist',
            name='events',
            field=models.ManyToManyField(related_name='artists', to='core.Event'),
        ),
    ]
