# Generated by Django 2.2.2 on 2019-07-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tickettype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.Tally'),
        ),
    ]
