# Generated by Django 2.2.2 on 2019-07-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190709_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='points',
        ),
    ]
