# Generated by Django 2.2.2 on 2019-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190616_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(related_name='events', to='core.Artist'),
        ),
    ]
