# Generated by Django 2.2.2 on 2019-06-11 12:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190611_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(default='www.facebook.com/test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(default='www.instagram.com/test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='soundcloud',
            field=models.URLField(default='www.soundcloud.com/test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='spotify',
            field=models.URLField(default='www.spotify.com/test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(default='www.twitter.com/test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(default='www.test.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.URLField(default='www.youtube.com/test'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
