# Generated by Django 2.2.3 on 2019-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190712_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.AddField(
            model_name='venue',
            name='address_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='address_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='address_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='address_zip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_zip',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
