# Generated by Django 2.2.3 on 2019-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190715_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address_line1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address_zip',
            field=models.CharField(max_length=255),
        ),
    ]
