# Generated by Django 2.2.3 on 2019-07-24 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='a1b2c3', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
